spring:
  datasource:
    url: jdbc:mysql://mysql:3306/feature_flags?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME:appuser}
    password: ${SPRING_DATASOURCE_PASSWORD:apppassword}
    
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

logging:
  level:
    com.featureflags: INFO
    org.springframework.web: INFO
